# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

boosting_stratify_core <- function(sample, delta, facility, num_facility, X, M_stop, rate, adj_variables) {
    .Call('_SurvBoost_boosting_stratify_core', PACKAGE = 'SurvBoost', sample, delta, facility, num_facility, X, M_stop, rate, adj_variables)
}

boosting_stratify_path <- function(sample, delta, facility, num_facility, X, M_stop, rate, adj_variables) {
    .Call('_SurvBoost_boosting_stratify_path', PACKAGE = 'SurvBoost', sample, delta, facility, num_facility, X, M_stop, rate, adj_variables)
}

boosting_stratify_numselected1 <- function(sample, delta, facility, num_facility, X, num_selected, rate, adj_variables) {
    .Call('_SurvBoost_boosting_stratify_numselected1', PACKAGE = 'SurvBoost', sample, delta, facility, num_facility, X, num_selected, rate, adj_variables)
}

boosting_stratify_likelihood1 <- function(sample, delta, facility, num_facility, X, rate, delta_likelihood, adj_variables) {
    .Call('_SurvBoost_boosting_stratify_likelihood1', PACKAGE = 'SurvBoost', sample, delta, facility, num_facility, X, rate, delta_likelihood, adj_variables)
}

boosting_stratify_BIC1 <- function(sample, delta, facility, num_facility, X, rate, early_stop, adj_variables, gamma, aic = FALSE) {
    .Call('_SurvBoost_boosting_stratify_BIC1', PACKAGE = 'SurvBoost', sample, delta, facility, num_facility, X, rate, early_stop, adj_variables, gamma, aic)
}

